# Cloud Build 설정 파일
# GCP에서 Docker 이미지를 빌드하고 Cloud Run에 배포하는 설정

steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/likelion-unified:latest'
      - '.'

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/likelion-unified:latest'

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'likelion-unified'
      - '--image'
      - 'gcr.io/$PROJECT_ID/likelion-unified:latest'
      - '--region'
      - 'asia-northeast3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--update-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},JWT_SECRET=${_JWT_SECRET}'
      - '--project'
      - '$PROJECT_ID'

images:
  - 'gcr.io/$PROJECT_ID/likelion-unified:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
